spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/amocloud_zipkin?characterEncoding=utf8&useSSL=false
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql
    
liaosj:
  hello: 你好！少杰！和田园！我还不信这下刷新还没有用！


