spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amocloud_zipkin?characterEncoding=utf8&useSSL=false
    schema: classpath:/mysql.sql
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: amocloud-mq-rabbit:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql


